/*
 * Copyright 2026 IVIR Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ivir.mms.testtool;

import java.awt.Color;
import java.util.List;

/**
 *
 */
public class BodyFluidsUpdaterDialog extends javax.swing.JDialog {

    /**
     * Creates new form BodyFluidsUpdaterDialog
     */
    public BodyFluidsUpdaterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initFields();
    }
    
    private void initFields(){
        this.attributeCb.addItem("Blood Loss");
        this.attributeCb.addItem("Blood Volume");
        this.attributeCb.addItem("Sweat Rate");
        this.attributeCb.addItem("Urine Output");
    }
    
    public BodyFluidsUpdaterDialog setInstanceCombo(List<BodyFluidsComboBoxItem> itemList){
       itemList.forEach((bodyFluids)->{
           this.objectsCb.addItem(bodyFluids.toString());
       });
       return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        objectsCb = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        attributeCb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        incrementTf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        durationTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Body Fluids Updater");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        startButton.setLabel("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton);

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton);

        cancelButton.setLabel("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cancelButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("For Object:");
        jPanel3.add(jLabel2);

        objectsCb.setPreferredSize(new java.awt.Dimension(200, 22));
        jPanel3.add(objectsCb);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Update: ");
        jPanel4.add(jLabel3);

        attributeCb.setMinimumSize(new java.awt.Dimension(100, 22));
        jPanel4.add(attributeCb);

        jLabel4.setText("by");
        jPanel4.add(jLabel4);

        incrementTf.setToolTipText("");
        incrementTf.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel4.add(incrementTf);

        jLabel5.setText("units");
        jPanel4.add(jLabel5);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("for");
        jPanel5.add(jLabel6);

        durationTf.setPreferredSize(new java.awt.Dimension(50, 22));
        jPanel5.add(durationTf);

        jLabel7.setText("seconds");
        jPanel5.add(jLabel7);

        jPanel2.add(jPanel5);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        this.incrementTf.setBackground(Color.WHITE);  
        this.durationTf.setBackground(Color.WHITE);
        
        float increment = 0;
        int duration = 0;
        try{
            increment = Float.parseFloat(this.incrementTf.getText());
        }catch(Exception e){
            this.incrementTf.setBackground(Color.red);
        }
        try{
            duration = Integer.parseInt(this.durationTf.getText());
        }catch(Exception e){
            this.durationTf.setBackground(Color.red);
        }
        if((increment != 0) && (duration != 0)){
            UiCommandHandler.getUiCommandHandler().modifyBodyFluidsUpdater(
                    this.objectsCb.getSelectedItem().toString().split(":")[0], 
                    true, this.attributeCb.getSelectedItem().toString(), 
                    increment, duration);
            this.setVisible(false);
        }
    }//GEN-LAST:event_startButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        UiCommandHandler.getUiCommandHandler().modifyBodyFluidsUpdater(
                this.objectsCb.getSelectedItem().toString().split(":")[0], 
                false, this.attributeCb.getSelectedItem().toString(), 
                null, null);
        this.setVisible(false);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BodyFluidsUpdaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BodyFluidsUpdaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BodyFluidsUpdaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BodyFluidsUpdaterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BodyFluidsUpdaterDialog dialog = new BodyFluidsUpdaterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> attributeCb;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField durationTf;
    private javax.swing.JTextField incrementTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> objectsCb;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    // End of variables declaration//GEN-END:variables
}
