/*
 * Copyright 2026 IVIR Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.ivir.mms.testtool;

import devstudio.generatedcode.datatypes.LevelOfConsciousnessEnum;
import devstudio.generatedcode.datatypes.LevelOfResponseEnum;
import java.awt.Color;

/**
 *
 */
public class NewUpdateNeuroScalesDialog extends javax.swing.JDialog {
    private String instanceName = null;

    public NewUpdateNeuroScalesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initializeLevelOfResponse(null);
        initializeLevelOfConsciousness(null);
        this.scaleTitleLabel.setText("New Neuro Scales");
        this.addButton.setText("Add");
    }
    
    public NewUpdateNeuroScalesDialog(java.awt.Frame parent, boolean modal, 
            String instanceName, String patientId, Integer eyes, Integer verbal, 
            Integer motor, String levelOfResponse, String levelOfConsciousness){
        super(parent, modal);
        initComponents();
        initializeLevelOfResponse(levelOfResponse);
        initializeLevelOfConsciousness(levelOfConsciousness);
        initializeGlasgowComaScale(eyes, verbal, motor);
        this.instanceName = instanceName;
        if(patientId != null){
            this.patientIdTf.setText(patientId);
        }
        this.scaleTitleLabel.setText("Update Neuro Scales");
        this.addButton.setText("Update");
    }
        
    private void initializeLevelOfResponse(String lorString){
        
        for(LevelOfResponseEnum lorEnum : LevelOfResponseEnum.values()){
            this.lorCb.addItem(lorEnum.toString());
        }
        if(lorString != null){
            this.lorCb.setSelectedItem(lorString);
        }
    }
    
    private void initializeLevelOfConsciousness(String locString){
        for(LevelOfConsciousnessEnum locEnum : LevelOfConsciousnessEnum.values()){
            this.locCb.addItem(locEnum.toString());
        }
        if(locString != null){
            this.locCb.setSelectedItem(locString);
        }
    }
    
    private void initializeGlasgowComaScale(Integer eyesInt, Integer verbalsInt, 
            Integer motorInt){
        if(eyesInt != null){
            this.eyesTf.setText(eyesInt.toString());
        }
        if(verbalsInt != null){
            this.verbalTf.setText(verbalsInt.toString());
        }
        if(motorInt != null){
            this.motorTf.setText(motorInt.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scaleTitleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        patientIdTf = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        eyesTf = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        verbalTf = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        motorTf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lorCb = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        locCb = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scaleTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scaleTitleLabel.setText("New Neuro Scales");
        getContentPane().add(scaleTitleLabel, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel7.setText("Patient ID:");
        jPanel9.add(jLabel7);

        patientIdTf.setMinimumSize(new java.awt.Dimension(150, 22));
        patientIdTf.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel9.add(patientIdTf);

        jPanel1.add(jPanel9);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Glasgow Scale"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Eyes:");
        jPanel6.add(jLabel4);

        eyesTf.setMinimumSize(new java.awt.Dimension(80, 22));
        eyesTf.setName(""); // NOI18N
        eyesTf.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel6.add(eyesTf);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Verbal:");
        jPanel7.add(jLabel5);

        verbalTf.setMinimumSize(new java.awt.Dimension(80, 22));
        verbalTf.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel7.add(verbalTf);

        jPanel3.add(jPanel7);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Motor:");
        jPanel8.add(jLabel6);

        motorTf.setMinimumSize(new java.awt.Dimension(80, 22));
        motorTf.setPreferredSize(new java.awt.Dimension(80, 22));
        jPanel8.add(motorTf);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Level of Response:");
        jPanel4.add(jLabel2);

        lorCb.setMinimumSize(new java.awt.Dimension(100, 22));
        lorCb.setPreferredSize(new java.awt.Dimension(100, 22));
        jPanel4.add(lorCb);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Level of Consciousness:");
        jPanel5.add(jLabel3);

        locCb.setMinimumSize(new java.awt.Dimension(120, 22));
        locCb.setPreferredSize(new java.awt.Dimension(120, 22));
        jPanel5.add(locCb);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addButton.setText("Add Neuro Scales");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        boolean readyToUpdate = true;
        
        Integer eyesNum = null;
        this.eyesTf.setBackground(Color.white);
        if((this.eyesTf.getText() != null) && (!this.eyesTf.getText().isEmpty())){
            try{
                eyesNum = Integer.parseInt(this.eyesTf.getText());
            }catch(Exception e){
                this.eyesTf.setBackground(Color.red);
                readyToUpdate = false;
            }
        }
        
        Integer verbalNum = null;
        this.verbalTf.setBackground(Color.white);
        if((this.verbalTf.getText() != null)&&(!this.verbalTf.getText().isEmpty())){
            try{
                verbalNum = Integer.parseInt(this.verbalTf.getText());
            }catch(Exception e){
                this.verbalTf.setBackground(Color.red);
                readyToUpdate = false;
            }
        }

        Integer motorNum = null;
        this.motorTf.setBackground(Color.white);
        if((this.motorTf.getText() != null)&&(!this.motorTf.getText().isEmpty())){
            try{
                motorNum = Integer.parseInt(this.motorTf.getText());
            }catch(Exception e){
                this.motorTf.setBackground(Color.red);
                readyToUpdate = false;
            }
        }
        
        if(readyToUpdate){
            this.setVisible(false);
            if(this.addButton.getText().equalsIgnoreCase("add")){
                UiCommandHandler.getUiCommandHandler().createNeuroScales(
                        this.patientIdTf.getText(), eyesNum, verbalNum, motorNum, 
                          (String) this.lorCb.getSelectedItem(), 
                          (String) this.locCb.getSelectedItem());
            }else{
                UiCommandHandler.getUiCommandHandler().updateNeuroScales(
                        this.instanceName, this.patientIdTf.getText(), eyesNum, 
                        verbalNum, motorNum,(String) this.lorCb.getSelectedItem(), 
                        (String) this.locCb.getSelectedItem());
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUpdateNeuroScalesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUpdateNeuroScalesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUpdateNeuroScalesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUpdateNeuroScalesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewUpdateNeuroScalesDialog dialog = new NewUpdateNeuroScalesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField eyesTf;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> locCb;
    private javax.swing.JComboBox<String> lorCb;
    private javax.swing.JTextField motorTf;
    private javax.swing.JTextField patientIdTf;
    private javax.swing.JLabel scaleTitleLabel;
    private javax.swing.JTextField verbalTf;
    // End of variables declaration//GEN-END:variables
}
